Implemented subset plots
angelolab/cell_classification pull request #24
Opened 2022-10-17 22:04 UTC by JLrumberger

**What is the purpose of this PR?**

This PR closes #23 . It contains code to prepare facet plots for arbitrary subsets of the cell-level predictions to get a clearer picture of error cases.

**How did you implement your changes**

I added functions `collapse_activity_dfs`, `subset_activity_df` and `subset_plots` to plot_utils.py and changed `calc_metrics` so that it does not internally defines function `calc_scores`, instead `calc_scores` is defined as a normal function so that I can get imported by `subset_plots`. 

**Remaining issues**

None

2022-10-17 22:35 UTC, JLrumberger commented
Found a small error when applying the code on real data, so I'll upload an updated version within the next couple of minutes.

2022-10-18 00:24 UTC, ngreenwald requested changes
Looks good, just a small tweak

2022-10-18 00:24 UTC, ngreenwald commented on cell_classification/plot_utils.py
> +        collapsed_df = pd.concat([collapsed_df, sample["activity_df"]])
It's faster to make a list and then perform a single concatenate call at the end https://github.com/angelolab/ark-analysis/issues/751

2022-10-18 20:55 UTC, ngreenwald approved these changes
Looks good!

2022-10-18 20:55 UTC, merged