Added worst n plots and heatmaps of per cell precision, recall, spec, f1
angelolab/cell_classification pull request #47
Opened 2023-01-25 18:20 UTC by JLrumberger

**What is the purpose of this PR?**

This PR closes #45 and adds functionality to automatically generate validation dataset performance metric plots and tables and visualizations of the worst n predictions. In a future PR this will be extended for the case of multiple validation datasets.

**How did you implement your changes**

A heatmap visualization of performance metrics split by marker or cell_type is added as `heatmap_plot` in `plot_utils.py`. Resulting plots look like this
![heatmap_split_by_marker](https://user-images.githubusercontent.com/22618181/214856899-3cd2c9bb-6aad-4ceb-a49e-870341371725.png)

Precision, recall, specificity and f1-scores vs. threshold are plotted together via `plot_metrics_against_threshold` instead of in a facetplot as written in the design doc #45. The resulting plots look like this:
![precision_recall_f1_cell_lvl](https://user-images.githubusercontent.com/22618181/214857529-125e1097-6953-4c42-aa96-eb6489e44c48.png)

I changed some bits in `evaluation_script.py` to plot the worst n predictions and to save the predicted cell_table. Worst n predictions are visualized like this:
![worst_0_MSK_colon_10b0e9ade389_Colon P20 CD3, Foxp1, PDL1, ICOS, CD8, panCK+CK7+CAM5 2__ 52459,17275 _image](https://user-images.githubusercontent.com/22618181/214858045-452753cf-99a4-4b25-971c-b9bdb9c61bc9.png)

**Remaining issues**

1. Is this really what we need for fast evaluation of our experiments or am I missing something?
2. I could've also included the functionality from `evaluation_script.py` as a class function in `ModelBuilder.py`, but I don't see a clear advantage of it yet. Do you have opinions on this?

2023-01-26 20:41 UTC, ngreenwald requested changes
This looks great. Plotting the worst images is a great idea, I think it'll really quickly help to hone in on issues.

2023-01-26 20:41 UTC, ngreenwald commented on cell_classification/evaluation_script.py
> +    worst_idx = np.argsort(roc["auc"])[-args.worst_n:]
I think there should be the option to do this by marker, in addition to global `worst_n`

2023-01-26 20:41 UTC, ngreenwald commented on cell_classification/evaluation_script.py
> +        "--worst_n",
I think having an option for `best_n` would be helpful as well to enable easy comparisons

2023-01-27 16:16 UTC, JLrumberger commented
Added the worst n / best n images and a flag to split them by marker. I had to do some ugly force pushes, because I worked from different computers without fetching the remote branch before making changes 😞

2023-01-27 17:40 UTC, ngreenwald approved these changes
Looks good!

2023-01-27 17:40 UTC, merged