Multi dataset
angelolab/cell_classification pull request #48
Opened 2023-01-26 14:48 UTC by JLrumberger

TBD

**What is the purpose of this PR?**

A clear description of what this PR is adding to the repository. Describe the bug that you've fixed or the new functionality that you've added. Ideally, this should be described in an existing issue on our [issues](https://github.com/angelolab/ark-analysis/issues) page. If so, make sure to includes `closes #issue_number` in the body of the description to properly link that issue. 

**How did you implement your changes**

A detailed description of what modifications you made to the codebase. Please include details on what functions you needed to change, how you changed them, and why. If you added new functions, give a description of what they do, as well as any specific design decisions

**Remaining issues**

If there are specific areas of your implementation that you feel need specific feedback, or if there are things you aren't sure about, please highlight them here

2023-02-09 20:20 UTC, ngreenwald commented
In terms of checking that this didn't inadvertently break anything, here are some options:
1. Use this branch to train a model on the TONIC dataset only, and check that the final confidence percentiles are equivalent to training with the single model code
2. Use this branch to train a model with the TONIC dataset plus 1 additional image from a different dataset, and check that the percentiles on the TONIC channels are equivalent. 
3. Duplicate the TONIC dataset into TONIC_1 and TONIC_2, and check that training with two datasets gives thresholds that are similar (but not exactly equal) to each other. Check that these probabilities are also similar to what we got before
4. For any of the above models, check the accuracy on the test dataset


Let me know what you think, or if you have other ideas for good sanity checks.

2023-02-09 20:28 UTC, ngreenwald requested changes
This was a monster! Awesome to see all the changes. Let me know what you think the best way to tease out any remaining bugs would be, and then once you're satisfied we can merge it in.

2023-02-15 11:20 UTC, JLrumberger commented
There seems to be a performance gap between baseline models trained with the old and the new codebase and I try to find the root cause.

2023-02-16 15:14 UTC, JLrumberger commented
Checked the datasets and they are identical except for the newly introduced nuclei and membrane channels.

2023-02-16 16:25 UTC, ngreenwald commented
So could it be a problem with how those channels are constructed? You’re still seeing a difference in performance for the same model on the old and new dataset?

2023-02-16 17:07 UTC, JLrumberger commented
old codebase, old dataset: not much jumps in validation loss
new codebase, old dataset: validation loss jumps to ~1.0 and goes down again
new codebase, new dataset: validation loss occasionally jumps to ~15-35 and goes down again

All of these models use the same parameters.. I am a bit suspicious now that it could be due to multi-gpu training. All models with the new codebase are trained on 4 GPUs..

2023-02-16 17:10 UTC, ngreenwald commented
I agree, we should try and change as few things as possible given that this PR is already so big. 

Were the models trained on the new dataset also using the nuclei/membrane channel? Or it was generated but not used during training?

2023-02-16 17:22 UTC, JLrumberger commented
> I agree, we should try and change as few things as possible given that this PR is already so big.
> 
> Were the models trained on the new dataset also using the nuclei/membrane channel? Or it was generated but not used during training?

The models were trained without the nuclei/membrane channel.

2023-02-16 17:31 UTC, ngreenwald commented
Okay, so to summarize:

- The code was changed to generate a nuclei and membrane channel, rather than just the target channel. However, the nuclei and membrane channels weren't included, and the rest of the dataset looks identical. 

- The code was changed to allow tracking of multiple different datasets. Even with only a single dataset, the output now sometimes looks much worse

- The models were trained on multiple GPUs, whereas before they were only trained on a single GPU. 


What's your hypothesis for why new codebase, new dataset looks different from new codebase, old dataset? Given that they are identical? Could this just be random noise from one bad training run?

2023-02-16 18:10 UTC, JLrumberger commented
Yep, I guess it's because of the initialization. I restarted all setups on single GPU..

2023-02-16 18:39 UTC, ngreenwald commented
Sounds good!

2023-02-17 16:52 UTC, JLrumberger commented
Oh god, it has been the multi GPU training. The loss for the baseline models looks normal when trained on a single GPU. PromixNaive models looks good as before. I just have one small little change to commit and then we can merge it in.

2023-02-17 17:41 UTC, ngreenwald commented
In addition to the training loss, will you run the test metrics and make sure there aren't any differences in performance?

Which of the above scenarios did you test out? Keeping the TONIC dataset the same, but training with the multi-dataset code?

2023-02-17 18:10 UTC, JLrumberger commented
I tested the following scenarios:

train baseline on tonic only with old dataset
train baseline on tonic only with new dataset
train baseline on tonic and decidua, sampling=[0.9999, 0.0001]
train baseline on tonic and tonic, sampling=[0.5, 0.5]

train promix on tonic only with new dataset
train promix on tonic and decidua, sampling=[0.9999, 0.0001]
train promix on tonic, decidua, msk_colon, sampling=[0.34, 0.33, 0.33]

so far I only looked at the validation loss and compared it to older models. I can calculate validation metrics and look for differences there, but it should look alright given the validation loss is similar as before.

2023-02-17 18:31 UTC, ngreenwald commented
Okay great! Sounds like you rooted out the problem. I think it'll just be better to be super sure that there aren't any lingering issues before we move forward.

2023-02-20 21:44 UTC, JLrumberger commented
@ngreenwald I am happy with this PR now.

2023-02-20 22:06 UTC, ngreenwald approved these changes
Great!

2023-02-20 22:06 UTC, merged